fix: remove duplicated old codes
This issue was introduced in: 3f3e4de5b066c938a9d1a4b740d8674b3d12a6a8

Fix by removing old codes and keep the new codes.

> ISO 639 is not a stable standard; some of the language codes it defines (specifically "iw", "ji", and "in") have changed. This constructor accepts both the old codes ("iw", "ji", and "in") and the new codes ("he", "yi", and "id"), but all other API on Locale will return only the OLD codes.

com.amaze.filemanager.ui.fragments.preferencefragments.UiPrefsFragmentTest > testDefaultBehaviour[28] FAILED
    java.lang.IllegalArgumentException: list[49] is a repetition
        at android.os.LocaleList.__constructor__(LocaleList.java:193)
        at android.os.LocaleList.<init>(LocaleList.java)
        at androidx.core.os.LocaleListCompat$Api24Impl.createLocaleList(LocaleListCompat.java:341)
        at androidx.core.os.LocaleListCompat.create(LocaleListCompat.java:77)
        at androidx.core.os.LocaleListCompat.forLanguageTags(LocaleListCompat.java:172)
        at com.amaze.filemanager.utils.ContextLocaleExtKt.getLocaleListFromXml(ContextLocaleExt.kt:53)
        at com.amaze.filemanager.utils.ContextLocaleExtKt.getLangPreferenceDropdownEntries(ContextLocaleExt.kt:62)
        at com.amaze.filemanager.ui.fragments.preferencefragments.UiPrefsFragment.onCreatePreferences(UiPrefsFragment.kt:55)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)